apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-1
spec:
  allowedCapabilities:
  - SYS_PTRACE
  - NET_ADMIN
  - NET_RAW
  allowedHostPaths:
  - pathPrefix: /data
    readOnly: true
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - hostPath
  - emptyDir
  - downwardAPI
  - projected
  - secret
  - persistentVolumeClaim
  - nfs