kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-1
  namespace: wordpress
subjects:
- kind: ServiceAccount
  name: sa-1
roleRef:
  kind: Role
  name: role-1
  apiGroup: rbac.authorization.k8s.io