kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-2
  namespace: wordpress
subjects:
- kind: ServiceAccount
  name: sa-2
roleRef:
  kind: Role
  name: role-2
  apiGroup: rbac.authorization.k8s.io