kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: wordpress
  name: role-2
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["psp-2"]
  verbs: [""]