kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pasha-rolebinding
  namespace: default
subjects:
- kind: User
  name: pasha-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pasha-role
  apiGroup: rbac.authorization.k8s.io